### ISSUE TITLE
[bug]: Client video window to join sharing not occurring

### ISSUE THREAD

**Issue by traviss182** [tonghohin/screen-sharing#10]
### Describe the bug

The screen-sharing web app is not functioning reliably. Specifically, the receiving computer often fails to load the video window when attempting to connect to the source. 
Do you observe the same behaviour on your side?
Attached are printscreens that there is no error in browser.

Browser: Edge
OS: Windows
Home network / personal laptops

### How to reproduce

1. Try to join sharing from computer 2.

### Screenshots

![client_console](https://github.com/user-attachments/assets/b71658f7-c66a-4435-a19e-617b6c326884)
![console_sources](https://github.com/user-attachments/assets/1ea8ace6-c7d7-4da1-9f8a-03e8198cf77d)
![source](https://github.com/user-attachments/assets/f48711bc-6fe8-49d5-a49d-611f81e9f40f)

**Comment by tonghohin** [comment]
I just tested the app several times with Edge and it's working fine for me. Is it just happening randomly for you?

**Comment by traviss182** [comment]
I guess so, two days ago it was working. Today i tried it from my deployment (older version) and your deployment and none of this was working. I also tried to share from PC1 and join on PC2 and opposite, non of this worked. 
Still the same 'Connecting' stage. So really do not now what can be an issue here. But you see it on the print screens that there is now video window. 
Is it working every time each day ?

**Comment by tonghohin** [comment]
Yes, it's been working for me all the time. That's strange, I can't really replicate the bug on my side. Does it work if you use another browser?

**Comment by traviss182** [comment]
Well, now it is working. I changed nothing, so yeah i don;t know what is the catch here. Closing since no error visible and hard to troubleshoot.
