### ISSUE TITLE
[feat]: use Artico for more Room features

### ISSUE THREAD

**Issue by matallui** [tonghohin/screen-sharing#2]
### Feature description

Hi! Thanks for sharing your project. It looks pretty cool! I see you’re using PeerJS but trying to use the concept of a Room, which I believe is not a feature they support.

So you have any plans on supporting other Room features, e.g., other people can share their screen as well, audio and video.

if so, I’d love for you to give [Artico](https://artico.dev) a try and let me know what you think.

**Comment by tonghohin** [comment]
Thanks for your feedback! I’m glad to hear you like my project! I’m pretty happy with how the app works right now, but I’ll definitely keep your suggestions in mind if I decide to expand things down the road.
