### ISSUE TITLE
[feat]: A square Icon for the app and favicon

### ISSUE THREAD

**Issue by mms-gianni** [tonghohin/screen-sharing#7]
### Feature description

A simple icon would enhance your app's recognizability and could also serve as a favicon.

the Icons should be square sized and about 400x400px of size. Having a SVG would help to have it resized

I could help you with the vectorizing and icon design. I helped with StirlingPDF logo to. https://github.com/Stirling-Tools/Stirling-PDF/issues/15 

### Additional Context

Some examples

![image](https://github.com/user-attachments/assets/4a6778e3-3718-45f3-bd8c-9ce8b46d7e8f)

**Comment by mms-gianni** [comment]
I used https://www.recraft.ai/ to generate them in case you want to try it yourself. I used up my free credits 😄

**Comment by tonghohin** [comment]
Thanks for the idea! But I enjoy how minimal the app looks right now without a logo. It certainly needs a favicon though, and I just put up a simple one, thanks for reminding me that!

**Comment by mms-gianni** [comment]
@tonghohin just make sure it is big enough to be used in template site from Kubero, Coolify, Portainer and RunTipi .
