### ISSUE TITLE
[bug]: Remote client still Connecting...

### ISSUE THREAD

**Issue by traviss182** [tonghohin/screen-sharing#8]
### Describe the bug

Hi,

when i join a room on Laptop2, it is still Connecting. Is it bug or am i missing something?
Should i changed something in the code to make this app work? I deployed it via Vercel.

Thanks

### How to reproduce

1. Create room on laptop1.
2. Join a room on laptop2.
3. Laptop1 informs that Lapto2 was connected
4. laptop2 is still Connecting

**Comment by traviss182** [comment]
In browser console i see error: Failed o load resource:net::ERR_BLOCKED_BY_CLIENT. (Clarity.ms/tag/p69zy6fidj) var ckarityw = window;

**Comment by tonghohin** [comment]
So is not working when you deploy it to Vercel? Is it working for you when you test it locally? 

The user flow is like this:
1. User 1 creates a room.
2. User 2 joins the room, and that should trigger a notification asking User 1 to share the screen.
3. After User 1 shared the screen, User 2 should be able to view it.

**Comment by traviss182** [comment]
@tonghohin correct, my deploy is not working in Vercel. I also tried your url [share-your-screen.vercel.app](https://share-your-screen.vercel.app/), not working aswell. Same behavior. 
Yes, the flow you wrote i would expect the same, but the step 3 is not working, User 2 is still in Connecting phase.

**Comment by tonghohin** [comment]
If you're behind a symmetric NAT like a corporate network, the peer connection would not work right now. Refer to the "Why am I unable to connect?" section at https://peerjs.com/docs/#start

And what browser are you using?

I have also just made a change to the app, it now logs the peer connection's errors and warnings. Can you give it a try again at [share-your-screen.vercel.app](https://share-your-screen.vercel.app/) and see if there're any errors in the console?

Thanks!

**Comment by traviss182** [comment]
yeah, that was the reason. Just tried on personal laptop and connected to a room from mobile and it is working. 
Thanks for pointing that out!
Great app, thanks!
